---
- name: Playbook ping localhost
  hosts: local
  tasks:
    - name: Ping localhost server
      ping:
    - name: Show variable 'ansible_test'
      debug:
        msg: "Varable 'ansible_test': {{ ansible_test }}"
      when: ansible_test is defined
